[project]
name = "bvd"
version = "0.1.0"
description = "Breaking Version Detector - Extensible tool for detecting breaking dependency version changes"
readme = "README.md"
authors = [{ name = "Your Name", email = "your.email@company.com" }]
requires-python = ">=3.10"
dependencies = ["packaging>=21.0", "python-hcl2>=4.0.0", "click>=8.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = ["pytest>=7.0", "black>=23.0", "ruff>=0.1.0"]

[project.scripts]
bvd = "bvd.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/bvd"]

[tool.ruff]
line-length = 100
select = ["E", "W", "F", "I"]

[tool.black]
line-length = 100
